version: "3.8"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cna
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_PRISMA_URL: postgresql://postgres:postgres@db:5432/cna
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres-data:
